/**
 * Deterministic head/tail/failure excerpt (PRD-014 Phase 1).
 *
 * Rule-based by construction: the four things §21 names as mandatory are facts
 * about the tool call, and the excerpt is derived from the bytes by rules, never
 * generated by a model.
 */

const FAILURE_PATTERN = /(error|failed|failure|exception|traceback|panic|assertion|not ok|✗|✘)/i;

export interface ExcerptOptions {
	headLines?: number;
	tailLines?: number;
	failureLines?: number;
	maxBytes?: number;
}

/**
 * First N lines, last N lines, and any lines that look like failures — deduped,
 * order-preserving, bounded by `maxBytes`.
 */
export function buildExcerpt(text: string, options: ExcerptOptions = {}): string {
	const headLines = options.headLines ?? 8;
	const tailLines = options.tailLines ?? 8;
	const failureLines = options.failureLines ?? 8;
	const maxBytes = options.maxBytes ?? 512;

	const lines = text.split("\n");
	const picked = new Set<number>();
	for (let index = 0; index < Math.min(headLines, lines.length); index += 1) picked.add(index);
	for (let index = Math.max(lines.length - tailLines, 0); index < lines.length; index += 1) picked.add(index);

	let failures = 0;
	for (let index = 0; index < lines.length && failures < failureLines; index += 1) {
		if (!FAILURE_PATTERN.test(lines[index]!)) continue;
		picked.add(index);
		failures += 1;
	}

	const ordered = [...picked].sort((left, right) => left - right);
	const rendered: string[] = [];
	let bytes = 0;
	for (const index of ordered) {
		const line = lines[index]!;
		if (bytes + Buffer.byteLength(line, "utf8") > maxBytes) break;
		rendered.push(line);
		bytes += Buffer.byteLength(line, "utf8") + 1;
	}
	if (rendered.length === 0 && lines.length > 0) return lines[0]!.slice(0, maxBytes);
	return rendered.join("\n");
}
